name: Uninstall Helm Release

inputs:
  release_name:
    required: true
    type: string
    description: Helm Release name
  cluster_name:
    required: true
    type: string
    description: Cluster name
  namespace:
    required: true
    type: string
    description: Namespace
  delete-namespace:
    required: true
    type: boolean
    default: true
  role-to-assume:
    required: true
    type: string
  aws-region:
    required: true
    type: string

runs:
  using: composite
  steps:

      - name: Set up Helm
        uses: azure/setup-helm@v4.0.0
        with:
            version: v3.8.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: ${{ inputs.role-to-assume }}
            role-session-name: "github-actions-runner"
            aws-region: ${{ inputs.aws-region }}
            role-skip-session-tagging: true

      - name: Update kubeconfig
        shell: bash
        run: aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region ${{ inputs.aws-region }}

      - name: Uninstall helm release
        id: uninstall
        shell: bash
        run: |
            helm uninstall -n ${{ inputs.namespace }} ${{ inputs.release_name }}

      - name: Delete Namespace
        if: ${{ inputs.delete-namespace == 'true' }}
        shell: bash
        run: |
            kubectl delete ns ${{ inputs.namespace }}

